model = 'gpt-5.4'
model_provider = "cust"

[history]
persistence = "save-all"

[model_providers.cust]
name = "cust"
base_url = "https://9527code.com/v1/"
env_key = "OPENAI_API_KEY"
wire_api = "responses"

[apps.codex_apps]
enabled = false